config/routes.rb
Rails.application.routes.draw do
  
  root to: 'articles#top'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :articles do
    
    collection do
      post :confirm
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  validates :content, presence: true
  validates :content, length: {maximum: 140 }

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
                    
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]
  
  #投稿一覧-----------------------------------
  def index
    @articles = Article.all
  end
  
  #投稿画面-----------------------------------
  def new
    if params[:back]
      @article = Article.new(article_params)
    else
      @article = Article.new
    end
  end
  
  #投稿---------------------------------------
  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path, notice:"一言投降完了！"
    else
      render 'new'
    end

  end
  
  
  #投稿編集-----------------------------------
  def edit

  end
  
  
  #投稿更新-----------------------------------
  def update

    if @article.update(article_params)
      redirect_to articles_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
    
  end
  
  
  #削除機能------------------------------------
  
  def destroy
    @article.destroy
    redirect_to articles_path, notice:"一言を削除しました"
  end
  
  #投稿確認------------------------------------
  def confirm
    @article = Article.new(article_params)
    render :new if @article.invalid?
  end
  
  
  
#---------------------------------------------
  private
  def article_params
    params.require(:article).permit(:content)
  end
  
  def set_article
    @article = Article.find(params[:id])
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'ログインに失敗しました'
        render 'new'
      end
      
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end
    
  def show
    @user = User.find(params[:id])
  end
  


#---------------------------------------------
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
                               
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_articles_path
    elsif action_name == 'edit'
      article_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<ul class="row">
  <li class="col-md-4"></li>
  <li class="col-xs-12 col-md-4">
    <%= form_with(model: @article, local: true ,url: choose_new_or_edit) do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explantion">
        <h2>投稿エラー</h2>
        <ul>
          <div class="alert alert-danger" role="alert">
            <%= @article.errors.full_messages %>
          </div>

        </ul>
      </div>
    <% end %>
      <div class="artilce_content">
        <center>
        <h3>140文字以内で一言！</h3>

          <div class="content">
            <%= form.label :一言 %>
            <%= form.text_field :content %>
          </div>
          <%= form.submit "投稿" ,:class=>"btn_submit" %>
          <% end %>
      </div>
  </li>
  </center>
  <li class="col-md-4"></li>
</ul>


  

app/views/articles/confirm.html.erb
<ul class="row">
  <li class="col-md-4"></li>
  <li class="col-xs-12 col-md-4">
    <center><h3>以下の内容で投稿する</h3>

    <%= form_with(model: @article, url: articles_path, local: true) do |form| %>
    <%= form.hidden_field :content %>

    <p>一言:<%= @article.content %></p>
    <%= form.submit  "投稿する" ,:class=>"btn_submit" %>
    <% end %>

    <%= form_with(model: @article, url: new_article_path, local: true, method: 'get') do |form| %>

    <%= form.hidden_field :content %>
    <%= form.submit "もどる" ,:class=>"btn_submit", name: 'back' %>
    <% end %>

    </center>
  </li>
  <li class="col-md-4"></li>
</ul>

app/views/articles/copyindex.html.erb
<table>
  <tr>
    <th><h1>一言一覧</h1></th>
    <p><%= notice %></p>
  </tr>
  
  <% @articles.each do |article| %>
  <tr>
    <div class="btn-group" role="group" aria-label="btn">
      <button type="button" class="btn btn-default"><%= link_to "一言を編集する", edit_article_path(article.id), data: { confirm: '本当に編集していいですか？' } %></button>
      <button type="button" class="btn btn-default"><%= link_to '一言を削除する', article_path(article.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></button>
    </div>
  </tr>
<% end %>
</table>

<%= link_to '一言を投稿する', new_article_path %>


<div class="btn-group" role="group" aria-label="btn">
  <button type="button" class="btn btn-default"><%= link_to "一言を編集する", edit_article_path(article.id), data: { confirm: '本当に編集していいですか？' } %></button>
  <button type="button" class="btn btn-default"><%= link_to '一言を削除する', article_path(article.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></button>
</div>

app/views/articles/edit.html.erb
<h2>一言投稿</h2>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
  <ul class="row">
    <li class="col-md-4"></li>
    <li class="col-xs-12 col-md-4">



      <table class="table table-striped">
        <tr><center><h1>一言一覧</h1></center>
          <div class="alert alert-success" role="alert">
            <p><%= notice %></p>
          </div>
        </tr>
        <div class="btn-group" role="group" aria-label="btn">
          <% @articles.each do |article| %>
            <tr>
              <td><%= article.content %></td>
              <td><button type="button" class="btn btn-default"><%= link_to "編集", edit_article_path(article.id), data: { confirm: '本当に編集していいですか？' } %></button></td>
             <td><button type="button" class="btn btn-default"><%= link_to '削除', article_path(article.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></button></td>
            </tr>
       
        <% end %>
        </div>
      </table>
      <div class="btn-group" role="group" aria-label="btn">
      　　<button type="button" class="btn btn-default"><%= link_to '一言を投稿する', new_article_path %>
　　　</div>

    </li>
    <li class="col-md-4"></li>
  </ul>

</div>

app/views/articles/new.html.erb
<center><h2>一言投稿</h2></center>

<%= render 'form' %>

app/views/articles/top.html.erb
<div class="top">
  <ul class="row">
    <li class="col-md-4"></li>
    <li class="col-xs-12 col-md-4">
      <center>
          <%= image_tag "chicken.gif" %>
         
      </center>     
          <h2>
            
         【このアプリについて】
              
          </h2>
          <h3>
              
                日頃言いたくても言えない事を
                一言でどんどん書き込もう！
          </h3>
        
        
        
       
    </li>
    <li class="col-md-4"></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>一言！</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <header>
      

    <% if logged_in? %>
      <ul class="nav nav-tabs">
        <li role="presentation"><%= link_to 'TOP', root_path %></li>
        <li role="presentation"><%= link_to '投稿一覧', articles_path %></li>
        <li role="presentation"><%= link_to '一言を投稿する', new_article_path %></li>
        <li align="right" role="presentation"><%= link_to 'プロフィール', user_path(current_user.id) %></li>
        <li align="right" role="presentation"><%= link_to 'ログアウト', session_path(current_user.id), method: :delete %></li>
      </ul>    


    </header>

    <% else %>

    　<%= link_to "アカウントを作成する", new_user_path %>
    　<%= link_to "ログイン", new_session_path %>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
     <% end %>
    <% end %>

    <%= yield %>

    <footer>
      <div class="footer">
      <center><p>2018年1月期生　小野貴裕</p></center>
      </div>
    </footer>

  </div>
</body>
</html>

app/views/users/new.html.erb
<h1>アカウントを作成する</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>